#ifndef ADC_cfg_H_
#define ADC_cfg_H_

#define ADC_STATUS                 ADC_ENABLE

#define ADC_VOLTAGE_REFERENCE      ADC_VREF_VCC

#define ADC_ADJUST_DEFINE          ADC_RIGHT_ADJUST

#define ADC_TRIGGER_DEFINE         ADC_AUTO_TRIGGER

#define ADC_AUTO_TRIGGER_SOURCE    ADC_FREE_RUNNING_MODE
 
#define ADC_CHANNEL_DEFINE         ADC_CHANNEL_0

#define ADC_PRESC_DEFINE           ADC_PRESC_128

#define ADC_INTERRUPT_DEFINE       ADC_INTERRUPT_DISABLE




#endif